[package]
name = "nasdaq"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
csv = "1.1.6"
ftp = { version = "3.0.1" }
graplot = "0.1.22"
polars = { version = "0.26.1", features = ["lazy", "csv-file", "strings", "temporal", "dtype-duration", "dtype-categorical", "concat_str", "rank", "lazy_regex"] }
rand = "0.8.5"
reqwest = "0.11.13"
yahoo-finance = "0.3.0"
